DATALOADER:
  TRAIN_X:
    BATCH_SIZE: 32
  TRAIN_U:
    BATCH_SIZE: 32
  TEST:
    BATCH_SIZE: 100
  NUM_WORKERS: 4

INPUT:
  SIZE: (224, 224)
  INTERPOLATION: "bicubic"
  PIXEL_MEAN: [0.48145466, 0.4578275, 0.40821073]
  PIXEL_STD: [0.26862954, 0.26130258, 0.27577711]
  RRCROP_SCALE: (0.5, 1.0)
  TRANSFORMS: ["random_resized_crop", "random_flip", "normalize"]

MODEL:
  BACKBONE:
    NAME: "ViT-B/16"

TRAINER:
  LIGHTNLPROMPT:
    N_CTX: 16
    CSC: False
    CTX_INIT: ""
    PREC: "fp16"
    CLASS_TOKEN_POSITION: "end"

    USE_SELECTOR: True
    SELECTOR_START_EPOCH: 20

    KEEP_RATIO: 0.45
    MIN_KEEP_TOKENS: 8
    MAX_KEEP_TOKENS: 184
    TOPR_QUERY_CLASSES: 3

    GUMBEL_TEMP: 1.0
    GUMBEL_MIN_TEMP: 0.3

    USE_RESIDUAL_TOKEN_LOGITS: True
    USE_TEXT_FIILM: False

    TOKEN_LOGIT_WEIGHT: 0.80
    LEARNABLE_TOKEN_GATE: True

    BUDGET_LOSS_WEIGHT: 0.001
    SELECTION_ENTROPY_WEIGHT: 0.0
    TEXT_REG_WEIGHT: 0.0

    LOG_TOKEN_STATS: True

OPTIM:
  NAME: "sgd"
  LR: 0.0005
  MAX_EPOCH: 100
  LR_SCHEDULER: "cosine"
  WARMUP_EPOCH: 1
  WARMUP_TYPE: "constant"
  WARMUP_CONS_LR: 1e-5
  WEIGHT_DECAY: 0.0005

TEST:
  FINAL_MODEL: "last_step"

TRAIN:
  PRINT_FREQ: 5
